
spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/data_clean
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: FieldService

eureka:
  client:
    service-url:
#      defaultZone: http://server:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090