server:
  port: 8761

spring:
  application:
    name: EurekaServer

eureka:
  instance:
#    hostname: server
    hostname: localhost
  client:
    service-url:
#      defaultZone: http://server:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
management:
  security:
    enabled: false
