server:
  port: 8762

spring:
  application:
    name: EurekaServer

eureka:
  instance:
    hostname: server2
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/